"""empty message

Revision ID: 186145bffed7
Revises: dd6714480bbe
Create Date: 2026-05-29 22:48:06.385226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186145bffed7'
down_revision = 'dd6714480bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimateRequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('materials_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimateRequest', schema=None) as batch_op:
        batch_op.drop_column('materials_json')

    # ### end Alembic commands ###
