"""empty message

Revision ID: 796f8a90e177
Revises: 95c023fe0bcf
Create Date: 2026-06-04 20:10:51.915603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796f8a90e177'
down_revision = '95c023fe0bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolioproject', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolioproject', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
