"""empty message

Revision ID: 95c023fe0bcf
Revises: 1bfb47b08d91
Create Date: 2026-06-04 19:59:27.134381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c023fe0bcf'
down_revision = '1bfb47b08d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolioproject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolioproject', schema=None) as batch_op:
        batch_op.drop_column('section')

    # ### end Alembic commands ###
