"""add estimate_type and breakdown json fields to invoice

Revision ID: a2010babbc00
Revises: 43bbf1cf0a7e
Create Date: 2026-06-22 00:08:51.783474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2010babbc00'
down_revision = '43bbf1cf0a7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimate_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('materials_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price_breakdown_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rooms_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('extras_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('extras_json')
        batch_op.drop_column('rooms_json')
        batch_op.drop_column('price_breakdown_json')
        batch_op.drop_column('materials_json')
        batch_op.drop_column('estimate_type')

    # ### end Alembic commands ###
