"""add estimate extras fields

Revision ID: dd6714480bbe
Revises: fc45d621772e
Create Date: 2026-05-26 22:30:21.546333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6714480bbe'
down_revision = 'fc45d621772e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimateRequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('furniture_rooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('furniture_heavy', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('moisture_barrier', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('floor_leveling', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('floor_leveling_mode', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('floor_leveling_bags', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('heavy_demo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('travel_miles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('use_flat_travel', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('price_breakdown_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimateRequest', schema=None) as batch_op:
        batch_op.drop_column('price_breakdown_json')
        batch_op.drop_column('use_flat_travel')
        batch_op.drop_column('travel_miles')
        batch_op.drop_column('heavy_demo')
        batch_op.drop_column('floor_leveling_bags')
        batch_op.drop_column('floor_leveling_mode')
        batch_op.drop_column('floor_leveling')
        batch_op.drop_column('moisture_barrier')
        batch_op.drop_column('furniture_heavy')
        batch_op.drop_column('furniture_rooms')

    # ### end Alembic commands ###
