"""add flooring protection and premium rates

Revision ID: fc45d621772e
Revises: 4323a444113f
Create Date: 2026-05-24 23:46:43.042363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc45d621772e'
down_revision = '4323a444113f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paint_removal_sqft', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('minimum_job_fee', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('travel_fee_per_mile', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('travel_fee_flat', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('furniture_moving_room', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('furniture_moving_heavy', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('moisture_barrier_sqft', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('floor_leveling_sqft', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('floor_leveling_bag', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('heavy_demo_sqft', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('backsplash_tile_sqft', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('shower_tile_sqft', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('shower_pan_each', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor_rates', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('shower_pan_each')
        batch_op.drop_column('shower_tile_sqft')
        batch_op.drop_column('backsplash_tile_sqft')
        batch_op.drop_column('heavy_demo_sqft')
        batch_op.drop_column('floor_leveling_bag')
        batch_op.drop_column('floor_leveling_sqft')
        batch_op.drop_column('moisture_barrier_sqft')
        batch_op.drop_column('furniture_moving_heavy')
        batch_op.drop_column('furniture_moving_room')
        batch_op.drop_column('travel_fee_flat')
        batch_op.drop_column('travel_fee_per_mile')
        batch_op.drop_column('minimum_job_fee')
        batch_op.drop_column('paint_removal_sqft')

    # ### end Alembic commands ###
