"""empty message

Revision ID: 080205319a21
Revises: a9919ce5b260
Create Date: 2026-03-22 20:12:44.466917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080205319a21'
down_revision = 'a9919ce5b260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='jobpriority'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('schedule_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estimate_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('idx_job_contractor_dates', ['contractor_id', 'schedule_date'], unique=False)
        batch_op.create_index('idx_job_priority', ['priority'], unique=False)
        batch_op.create_index('idx_job_status', ['status'], unique=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'])

    with op.batch_alter_table('job_documents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('idx_job_status')
        batch_op.drop_index('idx_job_priority')
        batch_op.drop_index('idx_job_contractor_dates')

    op.drop_table('job')
    # ### end Alembic commands ###
