"""empty message

Revision ID: 143863fd654c
Revises: 1b9d59a04179
Create Date: 2026-04-04 08:41:17.658950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '143863fd654c'
down_revision = '1b9d59a04179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoiceItem', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoiceItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
