"""empty message

Revision ID: 1b9d59a04179
Revises: 080205319a21
Create Date: 2026-04-02 23:36:49.673518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9d59a04179'
down_revision = '080205319a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('materials_needed',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('servicesMaterial', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('unit_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicesMaterial', schema=None) as batch_op:
        batch_op.alter_column('unit_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('materials_needed',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
