"""add portfolio hero_color btn_color

Revision ID: 1bfb47b08d91
Revises: 186145bffed7
Create Date: 2026-06-01 23:14:14.474646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bfb47b08d91'
down_revision = '186145bffed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_color', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('btn_color', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.drop_column('btn_color')
        batch_op.drop_column('hero_color')

    # ### end Alembic commands ###
