"""empty message

Revision ID: 24dfcae37e4f
Revises: 143863fd654c
Create Date: 2026-04-23 23:16:32.560864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24dfcae37e4f'
down_revision = '143863fd654c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('logo_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('cover_image',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('business_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('website_slug',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('about',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('stripe_onboarding_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('create_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.alter_column('create_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('stripe_onboarding_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('about',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('website_slug',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('business_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cover_image',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('logo_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
