"""add contractor rates

Revision ID: 4323a444113f
Revises: 75b9af8262b2
Create Date: 2026-05-24 22:52:03.073515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4323a444113f'
down_revision = '75b9af8262b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('paint_base_per_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('paint_extra_coat_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('paint_ceiling_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('paint_trim_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('paint_door_each', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('paint_window_each', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('paint_repair_surcharge', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('paint_color_change_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('paint_dark_to_light_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('floor_hardwood_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_engineered_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_laminate_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_vinyl_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_tile_ceramic_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_tile_porcelain_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_carpet_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_concrete_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_removal_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_baseboard_lft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_stair_each', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_transition_each', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floor_diagonal_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('floor_herringbone_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contractor_rates')
    # ### end Alembic commands ###
