"""Initial migration

Revision ID: ba330cb2a18e
Revises: 
Create Date: 2026-03-18 08:21:04.224273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba330cb2a18e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CONTRACTOR', 'CUSTOMER', name='userrole'), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('logo_image', sa.String(), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('business_email', sa.String(), nullable=False),
    sa.Column('website_slug', sa.String(length=500), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('payment_link', sa.String(length=500), nullable=True),
    sa.Column('subscription_status', sa.Enum('free', 'trial', 'active', 'past_due', 'canceled', name='subscriptionstatus'), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('subscription_renewal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=10), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.create_index('idx_contractor_verified', ['is_verified', 'subscription_status', 'plan_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contractor_subscription_status'), ['subscription_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contractor_website_slug'), ['website_slug'], unique=True)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_id', 'email')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('idx_customer_contractor', ['contractor_id', 'email'], unique=False)

    op.create_table('portfolioproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['contractor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('materials_needed', sa.String(), nullable=False),
    sa.Column('estimate_hours', sa.Float(), nullable=True),
    sa.Column('base_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_id', 'name', name='unique_service_per_contractor')
    )
    op.create_table('estimateRequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('new', 'converted', 'rejected', name='estimatestatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estimateRequest', schema=None) as batch_op:
        batch_op.create_index('idx_estimate_contractor_status', ['contractor_id', 'status'], unique=False)
        batch_op.create_index('idx_estimate_email', ['customer_email'], unique=False)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='jobpriority'), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('schedule_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estimate_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actual_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('idx_job_contractor_dates', ['contractor_id', 'schedule_date'], unique=False)
        batch_op.create_index('idx_job_priority', ['priority'], unique=False)
        batch_op.create_index('idx_job_status', ['status'], unique=False)

    op.create_table('portfolioimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolioproject_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolioproject_id'], ['portfolioproject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicesMaterial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'overdue', name='invoicestatus'), nullable=False),
    sa.Column('payment_link', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_link_id', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount = subtotal + tax', name='check_invoice_total'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contractor_id', 'invoice_number', name='uq_invoice_per_contractor')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index('idx_invoice_contractor_status', ['contractor_id', 'status'], unique=False)
        batch_op.create_index('idx_invoice_dates', ['issue_date', 'due_date'], unique=False)

    op.create_table('job_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['contractor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoiceItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=550), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('stripe', 'square', 'zelle', 'cash', 'check', name='paymentmethod'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'refunded', 'failed', name='paymentstatus'), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='check_payment_amount'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index('idx_payment_invoice', ['invoice_id'], unique=False)
        batch_op.create_index('idx_payment_status', ['payment_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index('idx_payment_status')
        batch_op.drop_index('idx_payment_invoice')

    op.drop_table('payment')
    op.drop_table('invoiceItem')
    op.drop_table('job_documents')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index('idx_invoice_dates')
        batch_op.drop_index('idx_invoice_contractor_status')

    op.drop_table('invoice')
    op.drop_table('servicesMaterial')
    op.drop_table('portfolioimage')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('idx_job_status')
        batch_op.drop_index('idx_job_priority')
        batch_op.drop_index('idx_job_contractor_dates')

    op.drop_table('job')
    with op.batch_alter_table('estimateRequest', schema=None) as batch_op:
        batch_op.drop_index('idx_estimate_email')
        batch_op.drop_index('idx_estimate_contractor_status')

    op.drop_table('estimateRequest')
    op.drop_table('services')
    op.drop_table('portfolioproject')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('idx_customer_contractor')

    op.drop_table('customer')
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contractor_website_slug'))
        batch_op.drop_index(batch_op.f('ix_contractor_subscription_status'))
        batch_op.drop_index('idx_contractor_verified')

    op.drop_table('contractor')
    op.drop_table('user')
    # ### end Alembic commands ###
