"""empty message

Revision ID: e13d69f2326f
Revises: 24dfcae37e4f
Create Date: 2026-04-23 23:21:20.444759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e13d69f2326f'
down_revision = '24dfcae37e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.alter_column('business_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('subscription_status',
               existing_type=postgresql.ENUM('free', 'trial', 'active', 'past_due', 'canceled', name='subscriptionstatus'),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('invoice_prefix',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.alter_column('invoice_prefix',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('subscription_status',
               existing_type=postgresql.ENUM('free', 'trial', 'active', 'past_due', 'canceled', name='subscriptionstatus'),
               nullable=False)
        batch_op.alter_column('is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('business_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
