"""reinit database

Revision ID: ea5930c83b4e
Revises: 
Create Date: 2026-05-09 00:33:36.622556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5930c83b4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimateRequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_address', sa.String(length=255), nullable=True),
    sa.Column('estimate_type', sa.Enum('painting', 'flooring', 'both', name='estimatetype', native_enum=False), server_default='painting', nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('preferred_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('new', 'converted', 'rejected', name='estimatestatus', native_enum=False), nullable=False),
    sa.Column('quoted_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contractor_notes', sa.String(length=500), nullable=True),
    sa.Column('total_sqft', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paint_surface_condition', sa.Enum('new_drywall', 'same_color', 'color_change', 'dark_to_light', 'damaged', name='paintsurfacecondition', native_enum=False), nullable=True),
    sa.Column('paint_coats', sa.Enum('one', 'two', 'three', name='paintcoats', native_enum=False), nullable=True),
    sa.Column('paint_type', sa.Enum('interior_standard', 'interior_premium', 'exterior_standard', 'exterior_premium', 'primer_only', name='painttype', native_enum=False), nullable=True),
    sa.Column('paint_finish', sa.Enum('flat', 'eggshell', 'satin', 'semi_gloss', 'gloss', name='paintfinish', native_enum=False), nullable=True),
    sa.Column('include_ceiling', sa.Boolean(), nullable=True),
    sa.Column('include_trim', sa.Boolean(), nullable=True),
    sa.Column('include_doors', sa.Boolean(), nullable=True),
    sa.Column('door_count', sa.Integer(), nullable=True),
    sa.Column('window_count', sa.Integer(), nullable=True),
    sa.Column('client_provides_paint', sa.Boolean(), nullable=True),
    sa.Column('desired_colors', sa.String(length=255), nullable=True),
    sa.Column('repairs_needed', sa.Boolean(), nullable=True),
    sa.Column('repairs_detail', sa.String(length=255), nullable=True),
    sa.Column('flooring_material', sa.Enum('hardwood', 'engineered_wood', 'laminate', 'vinyl_plank', 'tile_ceramic', 'tile_porcelain', 'carpet', 'concrete', name='flooringmaterial', native_enum=False), nullable=True),
    sa.Column('flooring_current', sa.Enum('bare_concrete', 'old_carpet', 'old_hardwood', 'old_tile', 'old_vinyl', 'already_removed', name='flooringcurrentstate', native_enum=False), nullable=True),
    sa.Column('include_removal', sa.Boolean(), nullable=True),
    sa.Column('subfloor_condition', sa.Enum('good', 'needs_repair', 'unknown', name='subfloorcondition', native_enum=False), nullable=True),
    sa.Column('flooring_pattern', sa.Enum('straight', 'diagonal_45', 'herringbone', 'chevron', name='flooringpattern', native_enum=False), nullable=True),
    sa.Column('include_baseboards', sa.Boolean(), nullable=True),
    sa.Column('transition_strips', sa.Integer(), nullable=True),
    sa.Column('include_stairs', sa.Boolean(), nullable=True),
    sa.Column('stair_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estimateRequest', schema=None) as batch_op:
        batch_op.create_index('idx_estimate_contractor_status', ['contractor_id', 'status'], unique=False)
        batch_op.create_index('idx_estimate_email', ['customer_email'], unique=False)
        batch_op.create_index('idx_estimate_type', ['estimate_type'], unique=False)

    op.create_table('estimate_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimateRequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('length_ft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('width_ft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('height_ft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimateRequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimate_room')
    op.drop_table('estimate_photo')
    with op.batch_alter_table('estimateRequest', schema=None) as batch_op:
        batch_op.drop_index('idx_estimate_type')
        batch_op.drop_index('idx_estimate_email')
        batch_op.drop_index('idx_estimate_contractor_status')

    op.drop_table('estimateRequest')
    # ### end Alembic commands ###
